# Generated by Django 5.2.10 on 2026-01-16 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('active_products', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('llc', 'LLC'), ('sole', 'Sole Proprietorship'), ('partnership', 'Partnership')], max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_contact', models.CharField(max_length=255)),
                ('phone_primary', models.CharField(max_length=50)),
                ('phone_secondary', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_methods', models.JSONField(default=list)),
                ('currency', models.CharField(max_length=10)),
                ('billing_cycle', models.CharField(max_length=50)),
                ('subscription_plan', models.CharField(max_length=50)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('products_count', models.PositiveIntegerField(default=0)),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('customer_count', models.PositiveIntegerField(default=0)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_metrics', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('documents_verified', models.JSONField(default=list)),
                ('kyc_status', models.CharField(max_length=50)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='merchants.merchant')),
            ],
        ),
    ]
