# Generated by Django 5.2.10 on 2026-01-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_activitymetrics_businessdetails_contactinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationstatus',
            name='kyc_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
