# Generated by Django 5.2.10 on 2026-01-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_alter_verificationstatus_kyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationstatus',
            name='kyc_status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
