# Generated by Django 5.2.10 on 2026-01-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_alter_verificationstatus_kyc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='financialinformation',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='platformmetrics',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='verificationstatus',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='ActivityMetrics',
        ),
        migrations.DeleteModel(
            name='BusinessDetails',
        ),
        migrations.DeleteModel(
            name='ContactInformation',
        ),
        migrations.DeleteModel(
            name='FinancialInformation',
        ),
        migrations.DeleteModel(
            name='PlatformMetrics',
        ),
        migrations.DeleteModel(
            name='VerificationStatus',
        ),
    ]
